basicapp/urls.py
from django.urls import path 
from basicapp import views
from django.contrib.auth import views as auth_views

app_name = 'basicapp'

urlpatterns = [
    path('registeration/',views.registration,name='registration'),
    path('user_login/',views.user_login,name='user_login'),
]

learining_users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from basicapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),
    path('ragistration/',views.registration,name='registration'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

basicapp/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class UserProfileInfo(models.Model):

    #Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    #Add additional attributes you want
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username
         

basicapp/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from django.forms.models import ModelForm
from basicapp.models import UserProfileInfo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
   

    class Meta():
        model = User
        exclude = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def registration(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.picture_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basicapp/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered}
                            )
    
def user_login(request):

     if request.method == 'POST':
         username = request.POST.get('username')
         password = request.POST.get('password')

         user = authenticate(username=username, password=password)
        
         if user:

            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

         else:
            print("Someone tries to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login details supplied!")

     else:

        return render(request,'basicapp/login.html',{})

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-light">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class='navbar-brand' href="{% url 'index' %}">DJANGO</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'registration' %}">Register</a></li>

                {% if user.is_authenticated %}
                    <li><a class='navbar-link' href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="navbar-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class='container'>
        {% block body_block %}
        {% endblock body_block %}
    </div>
    
</body>
</html> 

templates/basicapp/index.html
{% extends 'basicapp/base.html' %}
{% block body_block %}
<div class='jumbotron'>
    <h1>DJANGO Level five</h1>
</div>
{% endblock body_block %}

templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}

<div class='jumbotron'>
    <h1>Please Login</h1>
    <form action="{% url 'basicapp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">
    </form>
</div>


{% endblock body_block %}

templates/basicapp/registration.html
{% extends 'basicapp/base.html' %}

{% load static %}

{% block body_block %}

<div class='jumbotron'>
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form</h3>

        <form enctype="multipart/form-data" method='post'>
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p}}
            <input type="submit" name="" value="Register">
        </form>
    {% endif %}
</div>

{% endblock body_block %}